foruma/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('topics.urls'))
]

topics/urls.py
from django.urls import path
from django.contrib import admin
from . import views


urlpatterns = [
    path('', views.init, name="home"),
    path('topic/<int:pk>', views.topic, name="topic"),
    path('login', views.login, name="login"),
    path('lk', views.lk, name="lk"),
    path('exit', views.exit, name="exit")
]

topics/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Users(models.Model):
    name = models.CharField(max_length=20, help_text ="Введите ник пользователя", unique = True)
    password = models.CharField(max_length=100, null=True)
    ip = models.GenericIPAddressField(null=True, blank=True)
    token = models.CharField(max_length=40, null=True, blank=True)
    browser = models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return self.name


class Topics(models.Model):
    name = models.CharField(max_length=20, help_text ="Введите ник пользователя")
    created_by = models.ForeignKey('Users', on_delete=models.SET_NULL, null=True)
    is_topic = models.BooleanField()
    created_in = models.ForeignKey('Topics', on_delete=models.SET_NULL, null=True, blank=True)
    time = models.DateTimeField(auto_now = True)
    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('topic', args=[str(self.id)])

    def __str__(self):
        return str(self.id) + "." + self.name


class Messages(models.Model):
    text = models.CharField(max_length=20, help_text ="Введите ник пользователя")
    sended_by = models.ForeignKey('Users', on_delete=models.SET_NULL, null=True)
    in_topic = models.ForeignKey('Topics', on_delete=models.SET_NULL, null=True)
    time = models.DateTimeField(auto_now = True)

topics/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import Users#, Topics, Messages
from .auth import check_password

class SendingMessageForm(forms.Form):
    text = forms.CharField()


class AuthForm(forms.Form):
    login = forms.CharField()
    password = forms.CharField()
    def clean(self):
        data = super().clean()
        if 'login' not in data or 'password' not in data:
            raise ValidationError('Такого аккаунта не существует')

        login_to_check = data.get('login')
        password_to_check = data.get('password')
        user = Users.objects.filter(name=login_to_check)

        if not user:
            raise ValidationError('Такого аккаунта не существует')
        elif not check_password(password_to_check, user[0].password):
            raise ValidationError('Такого аккаунта не существует')
        return {"login":login_to_check, "password": password_to_check}
        


class SignUpForm(forms.Form):
    login = forms.CharField()
    password = forms.CharField()

    def clean_login(self):
        login_to_check = self.cleaned_data['login']

        if Users.objects.filter(name=login_to_check):
            raise ValidationError('Такой логин уже существует')
        return login_to_check

topics/views.py
from django.shortcuts import render
from .models import Users, Topics, Messages
from .forms import SendingMessageForm, AuthForm, SignUpForm
from django.http import HttpResponseRedirect
from django.urls import reverse
import uuid
from django.core.exceptions import ValidationError
from .auth import check_password, making_hash

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip 


def get_user_by_token(token, request):
    browser = request.META.get("HTTP_USER_AGENT", "")
    ip = get_client_ip(request)
    amount = Users.objects.filter(token=token)
    user = Users.objects.filter(token=token, browser=browser, ip=ip)
    return [user, amount]


def auth(request):
    token = request.session.get('token','')
    user = None
    amount = None
    if token != '':
        user, amount = get_user_by_token(token, request)
        user = user[0]
        if not user:
            if amount:
                amount.token=''
                amount.save()
            del request.session['token']
    
    return [request, user]


# Create your views here.
def init(request):
    request, user = auth(request)
    

    topics = Topics.objects.filter(created_in=None)
    # Отрисовка HTML-шаблона index.html с данными внутри
    # переменной контекста context
    return render(
        request,
        'index.html',
        context = {'topics': topics, 'user':user, 'topic':None},
    )


def topic(request, pk):
    request, user = auth(request)
    
    topic = Topics.objects.get(id=pk)
    
    # Если контейнер (внутри есть ещё темы)
    if Topics.objects.filter(created_in=pk).count() != 0:
        topics = Topics.objects.filter(created_in=pk)
        return render(
            request,
            'index.html',
            context = {'topics': topics, "user":user, 'topic':topic},
        )


    # Отправка сообщения
    if request.method == "POST" and user:
        form = SendingMessageForm(request.POST)
        if form.is_valid():
            Messages.objects.create(text = form.cleaned_data['text'], sended_by=user, in_topic=topic)
            return HttpResponseRedirect(reverse('topic',args=[pk]) )
    
    # Просмотр темы форума
    outer = request.GET.get("outer",0)
    messages = topic.messages_set.all()#[outer:outer+10]
    form = SendingMessageForm()
    print("ALL GOOD", topic)
    return render(
        request,
        'topic.html',
        context = {'topic': topic,
        "messages":messages, "form":form, "user":user},
    )


def login(request):
    request, user = auth(request)
    if user:
        return HttpResponseRedirect(reverse('lk') )
    
    form = AuthForm()

    if request.method == "POST":
        if "type" in request.POST:

            if request.POST['type'] == 'LogIn': 
                form = AuthForm(request.POST)
            
            else:
                form = SignUpForm(request.POST)
        

            if form.is_valid():
                if request.POST['type'] == 'SignIn':
                    user = Users.objects.create(name=form.cleaned_data['login'], password=making_hash(cleaned_data['password']))

                user = Users.objects.filter(name=form.cleaned_data['login'])
                if user:
                    user = user[0]
                    user.ip = get_client_ip(request)
                    user.browser = request.META.get("HTTP_USER_AGENT", "")
                    user.token = uuid.uuid4()
                    user.save()
                    request.session['token'] = str(user.token)
                    return HttpResponseRedirect(reverse('home') )

    return render(
        request,
        'sign_in.html',
        context = {"form":form, "user":user},
    )
    


def lk(request):
    request, user = auth(request)

    if not user:
        return HttpResponseRedirect(reverse('login') )
    
    if request.method == "POST":
        del request.session['token']
        user.token = ''
        user.save()
        return HttpResponseRedirect(reverse('home') )

    return render(
        request,
        'lk.html',
        context = {"user":user}
    )


def exit(request):
    request, user = auth(request)

    if user:
        del request.session["token"]
        user.token = ''
        user.save()
    
    
    return HttpResponseRedirect(reverse('home') )


# from django.views import generic

# class TopicsDetailView(generic.DetailView):
#     model = Topics

topics/templates/base_index.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block title %}<title>Foruma</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS (jsDelivr CDN) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"><!-- Bootstrap Bundle JS (jsDelivr CDN) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  
</head>

<body>

    <div class="container-fluid">

        <div >
            {% block topbar %}
            
            <ul class="nav nav-pills nav-fill">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'home' %}">Home</a>
                </li>
                <a class="nav-item" href="#">
                    <img src="/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" alt="">
                </a>
                <li class="nav-item">
                    {% if user %}
                    <a class="nav-link" href="{% url 'lk' %}">L2K</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'login' %}">LK</a>
                    {% endif %}
                </li>
            </ul>
            {% endblock %}
        </div>
        <div >
            {% if topic %}
            <!-- <ul> -->
                <a href="{% url 'home' %}">Home</a>
                {% include "tree.html" %}
            <!-- </ul> -->
            {% endif %}
            {% block content %}{% endblock %}
        </div>

        <!-- {% block pagination %}

        {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
        {% endblock %}  -->
    </div>
</body>
</html>

topics/templates/index.html
{% extends "base_index.html" %}

{% block content %}
    <div style="margin-left:20px;margin-top:20px">
        
        
        <h4>Темы:</h4>

        {% for topic in topics %}
            <hr>
            <p style="padding:0;margin:0"><h4><a href="{{ topic.get_absolute_url }}">{{ topic.name }}</a></h4></p>
            {% if topic.topics_set.last %}
                <p style="padding:0;margin:0"><strong>Inside:</strong> {{topic.topics_set.count}} topic(s)</p>
            {% else %}
                <!-- <p style="padding:0;margin:0"><strong>Created:</strong> {{topic.time}}</p> -->
                {% if topic.messages_set.last %}
                    <p><strong>Last message:</strong> {{topic.messages_set.last.time}}</p>
                {% else %}
                    <p><strong>Last message:</strong> be first</p>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

topics/templates/lk.html
{% extends "base_index.html" %}

{% block content %}
    <div style="margin-left:20px;margin-top:20px">
        {% if user %}
        <h4>Личный кабинет</h4>
        <p>{{user}}</p>
        
        <a href="{% url 'exit' %}">Выйти</a>
        {% endif %}
    </div>
{% endblock %}

topics/templates/sign_in.html
{% extends "base_index.html" %}

{% block content %}
    <div style="margin-left:20px;margin-top:20px">
        <h4>Авторизация</h4>
        {% if form %}
        <form action="" method="post">
            {% csrf_token %}
            <table>
            {{ form }}
            </table>
            <input type="submit" value="LogIn" name="type"/>
            <input type="submit" value="SignIn" name="type"/>
        </form>
        {% endif %}
    </div>
{% endblock %}

topics/templates/topic.html
{% extends "base_index.html" %}

{% block content %}
    <div style="margin-left:20px;margin-top:20px">
        
        
        <h4>Тема: {{topic.name}}</h4>

        {% for message in messages %}
            <hr>
            <p style="padding:0;margin:0"><h4>{{ message.text }}</h4></p>
            <p style="padding:0;margin:0"><strong>Created:</strong> {{message.sended_by}}</p>
            
        {% endfor %}
        <hr>
        {% if form and user %}
        <form action="" method="post">
            {% csrf_token %}
            <table>
            {{ form }}
            </table>
            <input type="submit" value="Submit" />
        </form>
        {% else %}
        <p>Для отправки сообщёния нужно авторизироваться</p>
        {% endif %}
    </div>
{% endblock %}

topics/templates/tree.html
{% if topic.created_in %}
        {% with "tree.html" as filename %}
        {% with topic.created_in as topic %}
            {% include filename %}
        {% endwith %}
        {% endwith %}
    {% endif %}
    -><a href="{{topic.get_absolute_url}}">{{ topic.name }}</a>